# Streamlit Secrets Configuration
# Add your actual API keys here for local development

# Google API Key for Gemini
GOOGLE_API_KEY = "AIzaSyBUdEgO4KT3HLN1qAvtJYCod3eCOw8Q_LU"

# Optional: OpenAI API Key (if you want to use OpenAI instead)
# OPENAI_API_KEY = "your_openai_api_key_here"

# Optional: Other configuration
# MODEL_TYPE = "gemini"  # or "openai"
