# Streamlit Secrets Configuration
# This file is not needed since we're using hardcoded API keys
# But keeping it for reference

# Google API Key for Gemini (hardcoded in app.py)
# GOOGLE_API_KEY = "your_api_key_here"
